openapi: 3.0.0
info:
  title: Storage Service API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /health:
    get:
      summary: Check service health
      responses:
        '200':
          description: OK
  /readings:
    get:
      summary: (pendiente) Consulta de lecturas
      responses:
        '200':
          description: OK

