version: '3.8'
services:
  broker:
    image: eclipse-mosquitto:2.0
    container_name: broker-mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"  
    volumes:
      - ./broker-mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - iot_net

  middleware:
    build: ./middleware
    container_name: middleware
    restart: always
    ports:
      - "8080:8080" 
    environment:
      - MQTT_BROKER=broker
      - MQTT_PORT=1883
    depends_on:
      - broker
    networks:
      - iot_net

  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot_net
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot_net
    depends_on:
      - influxdb

networks:
  iot_net:

volumes:
  influxdb_data:
